### ISSUE TITLE
Exclude list for sources to mutate

### ISSUE THREAD

**Issue by AlexanderWinter** [ComparetheMarket/fettle#68]
This is not an issue, but a wish for an exclude filter:

So far it is possible to include source files and folder and that works very well, but we typically have our tests in a subfolder named 'Test' within the source project. Of course we could create sourceFileFilters for all files and folders that contain sources and leave the 'Test' folder out, but if we add additional sources and sourcefolders, we do have to adapt the config file every time. 

So it would be much nicer to be able to simply exclude the 'Test' folder.

**Comment by oliwennell** [comment]
Hi @AlexanderWinter thanks for raising. I can see how this would be a useful feature.
I'll have a think about what work would be required and post it here.

**Comment by oliwennell** [comment]
If we were to add a new, separate, configuration option (called something like "sourceFileExclusionFilters" perhaps), then the work required would be something like this:

1. Add config option for an exclusion filter in the config file model:

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Console/ConfigFile.cs#L19

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Tests/Console/ImplementationDetails/Config_file_parsing.cs#L9

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Tests/Console/Invalid_config.cs#L9

...and the internal model:

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Core/Config.cs#L22

2. Update filtering logic to take the exclusion filter into account

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Core/Internal/Filtering.cs#L30

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Tests/Core/ImplementationDetails/ShouldMutateDocument_Tests.cs#L7

3. Update an end-to-end test to have a single source file exclusion, in order to verify exclusion filters are correctly passed all the way from the code reading the config file to the code calling the filtering logic.

4. Update documentation on the wiki

**Comment by oliwennell** [comment]
Another option would be to keep the existing `sourceFileFilters` option but allow this to contain inclusions _and_ exclusions (it currently only allows inclusions). If we did this we'd need some way (ideally backwards-compatible) of specifying which filters were exclusions. Not sure how best to do that.

**Comment by oliwennell** [comment]
After thinking about it, the second option seems best to me.

It would be the more obvious solution, and be easier to implement too :)

Changes would just be to `ShouldMutateAccordingToFilters` and its unit tests:

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Core/Internal/Filtering.cs#L30

https://github.com/ComparetheMarket/fettle/blob/e513360b871a7a696f9832c62cb8fc90b01de0ae/src/Tests/Core/ImplementationDetails/ShouldMutateDocument_Tests.cs#L7

It will probably take me a while to get around to this. However, I'd be happy to accept a pull request from you if you wanted @AlexanderWinter ?

**Comment by AlexanderWinter** [comment]
Thank you for the nice invitation. I'll see what I can do...

**Comment by oliwennell** [comment]
Fixed in v0.7.0
